# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('vote_limit', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionsCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidates_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Candidates')),
                ('elections_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Elections')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionsPriviliged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('elections_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Elections')),
            ],
        ),
        migrations.CreateModel(
            name='Electors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='electionspriviliged',
            name='electors_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Electors'),
        ),
        migrations.AddField(
            model_name='elections',
            name='candidates',
            field=models.ManyToManyField(through='mainapp.ElectionsCandidates', to='mainapp.Candidates'),
        ),
        migrations.AddField(
            model_name='elections',
            name='voters',
            field=models.ManyToManyField(through='mainapp.ElectionsPriviliged', to='mainapp.Electors'),
        ),
    ]
