# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170406_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionscandidates',
            old_name='candidates',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='electionscandidates',
            old_name='elections',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='electionspriviliged',
            old_name='elections',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='electionspriviliged',
            old_name='electors',
            new_name='elector',
        ),
    ]
